[build]
  # Since this is a Python server app, Netlify is not ideal
  # This file is included for reference if you create a separate frontend
  publish = "public"
  command = "echo 'This is a Python server application - use Render instead'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"
