services:
  - type: web
    name: cvss-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
